"Updated offensive behaviors, and…
CLSFramework/py-agent-2d pull request #3
Opened 2024-12-04 20:54 UTC by ErfanFathii

… modified KickDecisionMaker to use BhvStarterKickPlanner."

2024-12-05 00:16 UTC, naderzare requested changes

2024-12-05 00:16 UTC, naderzare commented on src/behaviors/bhv_starter_pass.py
> +class Pass(IBehavior):
class name should be BhvStarterPass

2024-12-05 00:16 UTC, naderzare commented on src/behaviors/bhv_starter_dribble.py
> +class Dribble(IBehavior):
BhvStarterDribble

2024-12-05 00:16 UTC, naderzare commented on src/behaviors/bhv_starter_clearball.py
> +class ClearBall(IBehavior):
Bhv...

2024-12-05 00:16 UTC, naderzare commented on src/decision_makers/kick_decision_maker.py
> +        #self.bhv_kick_planner.execute(agent)
we do not need this line

2024-12-05 00:16 UTC, naderzare commented on src/decision_makers/kick_decision_maker.py
> +        self.bhv_kick_planner = BhvStarterKickPlanner()
for default we should not use Starter classes, but we can have a variable in sample player agent, for example starter=true/false and we can choose planner or starter planner based on that variable

2024-12-06 10:04 UTC, SoroushMazloum reviewed
I fixed these issues in my new commit

2024-12-08 12:45 UTC, SoroushMazloum approved these changes

2024-12-08 12:47 UTC, SoroushMazloum approved these changes

2024-12-16 02:54 UTC, closed without merging